heat_template_version: 2013-05-23

description: >
  HOT Template to create the AIM instances attached to a NEW router and NEW network/subnet.

parameters:
  Key_name:
    type: string
    description: Name of keypair to assign to servers
    default: rgb_heat
  Private_net_name:
    type: string
    description: Name of private network to be created
  public_net:
    type: string
    description: Name of private network to be created
  private_subnet:
    type: string
    description: Name of private network to be created
  private_net:
    type: string
    description: Name of private network to be created
  ADS_address:
    type: string
    description: Name of ADS server
  OSS_address:
    type: string
    description: Name of OSS server
  Sources_address:
    type: string
    description: Name Repository Server
  pool_id:
    type: string
    description: ID of LB pool
  Image_name:
    type: string
    description: Image to use
    default: RGB_CentOS-6.3_17601_Cloud
  PS_flavor:
    type: string
    description: Flavor to use for PS
    default: m1.RGB_Large
    constraints:
        - allowed_values:
          - m1.RGB_Small
          - m1.RGB_Medium
          - m1.RGB_Large

resources:

  PS_AS:
    type: OS::Heat::AutoScalingGroup
    properties:
      resource:
        type: "http://192.155.251.107/heat/aim/v1/ps_server_v2.yaml"
        properties:
            public_net: { get_param: public_net }
            private_net: { get_param: private_net }
            private_subnet: { get_param: private_subnet }
            Sources_address: { get_param: Sources_address }
            ADS_address: { get_param: ADS_address }
            OSS_address: { get_param: OSS_address }
            Key_name: { get_param: Key_name }
            Image_name: { get_param: Image_name }
            PS_flavor: { get_param: PS_flavor }
            pool_id: { get_param: pool_id }
      min_size: 1
      desired_capacity: 1
      max_size: 10

  scale_up_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: PS_AS}
      cooldown: 30
      scaling_adjustment: 1

  scale_down_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: PS_AS}
      cooldown: 30
      scaling_adjustment: '-1'

outputs:
  scale_up_url:
    description: >
      This URL is the webhook to scale up the group.  You can invoke
      the scale-up operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [scale_up_policy, alarm_url]}
  scale_dn_url:
    description: >
      This URL is the webhook to scale down the group.  You can invoke
      the scale-down operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [scale_down_policy, alarm_url]}
